version: '3'

services:
  web:
    image: givemebape/ldap-notify:latest
    command: >
      gunicorn --bind 0.0.0.0:8000
               --workers 4
               --preload
               ldap_notify.wsgi:application
    environment:
      - TZ=Europe/Moscow
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - AUTH_LDAP_BIND_DN=${AUTH_LDAP_BIND_DN}
      - AUTH_LDAP_BIND_PASSWORD=${AUTH_LDAP_BIND_PASSWORD}
      - AUTH_LDAP_BASE_DN=${AUTH_LDAP_BASE_DN}
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  celery:
    image: givemebape/ldap-notify:latest
    command: celery -A ldap_notify worker -l info
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    env_file:
      - .env
    depends_on:
      - redis
      - web
    restart: unless-stopped

  celery-beat:
    image: givemebape/ldap-notify:latest
    command: celery -A ldap_notify beat -l info
    depends_on:
      - redis
      - web
    restart: unless-stopped